Repository discord-math/discord-math.github.io, pull requests merged in 2022-12, with the labels that each got.

#5 Add events-guidelines
  events-guidelines.md
  static/img/events-guidelines/publish.png
Labels: addition, content

#10 Allow extra CSS to be specified per page
  _includes/extra_styles/hero.css
  _includes/head.html
  _layouts/home.html
  index.md
Labels: addition, code

#8 Add /books
  _books/abstract-algebra.md
  _books/algebraic-geometry.md
  _books/algebraic-topology.md
  _books/calculus.md
  _books/category-theory.md
  _books/combinatorics.md
  _books/commutative-algebra.md
  _books/complex-analysis.md
  _books/dynamical-systems.md
  _books/functional-measure-harmonic.md
  _books/galois-theory.md
  _books/lie-theory.md
  _books/linear-algebra.md
  _books/logic-and-foundations.md
  _books/number-theory.md
  _books/numerical-analysis.md
  _books/odes.md
  _books/pdes.md
  _books/point-set-topology.md
  _books/probability.md
  _books/proofs.md
  _books/real-analysis.md
  _config.yml
  books.md
Labels: addition, content

#11 Enforce US spelling
  _books/abstract-algebra.md
  _books/category-theory.md
  _books/commutative-algebra.md
  _books/functional-measure-harmonic.md
  _books/pdes.md
  _books/point-set-topology.md
  _books/real-analysis.md
  info.md
  rules.md
Labels: content, update

#12 Add highlight CSS (closes #9)
  _includes/extra_styles/highlight.css
Labels: addition, code

#6 Add helper-guidance
  helper-guidance.md
Labels: addition, content
